# ***CS 512 -- COMPUTER VISION -- FIRST ASSIGNMENT***


---


***Fall 2024, 09/22/2024***

**Antonio Castañares A20599898**



In [1]:
#pip3 install opencv-python
import numpy as np
import cv2 as cv

***First Question:***

**Homogeneous Coordinates Representation (2D)**:  Let **x = (2,3)** be
a point in 2D Cartesian coordinates.

• Convert the point x into homogeneous coordinates **$x_{h}$**.

• Find another point in 2D homogeneous coordinates that is equivalent
to the same point **x** (use a different scale).

• Convert both homogeneous coordinates back to Cartesian coordinates and verify they represent the same point.

In [2]:
# Initilization
x = np.array([2, 3])

# Convert the point x into homogeneous coordinates  xh
x_h = np.append(x, 1)

# Find another point in 2D homogeneous coordinates that is equivalent to the same point x (use a different scale).
equivalent_x_h = x_h * 2

# Convert both homogeneous coordinates back to Cartesian coordinates and verify they represent the same point.
cartesian_x_h = x_h[:2] // x_h[2]
cartesian_equivalent_x_h = equivalent_x_h[:2] / equivalent_x_h[2]

# Comprobations
print("Result first point: ",x_h)
print("Result second point: ",equivalent_x_h)
print(f"Result third point: x = {x}, first homogeneous coordinate: {cartesian_x_h}, second homogeneous coordinate: {cartesian_equivalent_x_h}")
print("---Comprobations---")
print(f"Are each result correct? {np.array_equal(x, cartesian_x_h)} and {np.array_equal(x,cartesian_equivalent_x_h)}")



Result first point:  [2 3 1]
Result second point:  [4 6 2]
Result third point: x = [2 3], first homogeneous coordinate: [2 3], second homogeneous coordinate: [2. 3.]
---Comprobations---
Are each result correct? True and True


***Second question:***

**Homogeneous Coordinates Representation (3D):** Let **y = (4,5,6)**
be a point in 3D Cartesian coordinates.

• Convert **y** to its homogeneous coordinates representation.

• Now, consider the homogeneous point yh = (4, 5, 6, 1). Scale it by a
factor of 2 and convert back to Cartesian coordinates.

• Verify the result matches the original point **y**.

In [3]:
# Initialization
y = np.array([4,5,6])

# Convert y to its homogeneous coordinates representation.
y_h = np.append(y, 1)

# Now, consider the homogeneous point yh = (4, 5, 6, 1). Scale it by a factor of 2 and convert back to Cartesian coordinates.
scaled_y_h = y_h * 2
cartesian_scaled_y_h = scaled_y_h[:3] / scaled_y_h[3]

# Verify the result matches the original point y.
print(f"Result first point: y = {y}, y_h = {y_h}")
print(f"Result second point: scaled_y_h = {scaled_y_h}, cartesian_scaled_y_h = {cartesian_scaled_y_h}")
print("---Comprobations---")
print(f"Are the result correct? {np.array_equal(y, cartesian_scaled_y_h)}")

Result first point: y = [4 5 6], y_h = [4 5 6 1]
Result second point: scaled_y_h = [ 8 10 12  2], cartesian_scaled_y_h = [4. 5. 6.]
---Comprobations---
Are the result correct? True


***Third question:***

**Affine Transformations in 2D:** Given a point **p = (1,2)** in 2D, apply
the following transformations in the specified order:

• Scale by a factor of 3.

• Rotate counterclockwise by 45◦.

• Translate by (2,3)

Compute the transformation matrix in homogeneous coordinates for
each step. Then, apply the combined transformation to the point
**p**. Finally, verify your result by applying the transformations using
NumPy.

In [4]:
"""
  This function applies an affine transformation to a point in 2D. It uses in questions 3 and 4 to avoid redundant code.
  Parameters:
    point: The point to be transformed.
    scale: The scale factor.
    angle: The angle of rotation in degrees.
    translation: The translation vector.
    inverse_path: If True, the transformation is applied in reverse order.
  Returns:
    The transformed point.
"""

def affine_transformation(point,scale,angle,translation,inverse_path):
  # Initializations
  p_h = np.array([point[0],point[1],1])

  # Scale by a factor
  scale_matrix = np.array([[scale,0,0],[0,scale,0],[0,0,1]])

  # Rotate counterclockwise by
  rotation_matrix = np.array([[np.cos(np.radians(angle)), -np.sin(np.radians(angle)), 0],[np.sin(np.radians(angle)), np.cos(np.radians(angle)), 0],[0,0,1]])

  # Translate by
  translation_matrix = np.array([[1,0,translation[0]],[0,1,translation[1]],[0,0,1]])

  # Final transportation matrix
  if(not inverse_path):
    transformation_matrix = translation_matrix @ rotation_matrix @ scale_matrix
  else:
    transformation_matrix = scale_matrix @ rotation_matrix @ translation_matrix

  # Final result
  result = transformation_matrix @ p_h

  return np.array([result[0] / result[2], result[1] / result[2]])


# Results:
x,y = affine_transformation(np.array([1,2]),3,45,np.array([2,3]),False)
print(f"Final position: x = {x}, y = {y}")


Final position: x = -0.12132034355964283, y = 9.36396103067893


***Fourth question:***

**Inverse Transformations (2D):** Let **q = (3,4)** be a point in 2D, and
assume the following transformations have been applied:

• Scale by 2.

• Rotate by 30◦.

• Translate by (5,5).

Compute the matrix that reverses these transformations. Apply the
inverse matrix to return **q** to its original position. Verify the result
using Numpy.

In [5]:
# Initializations
q = np.array([3,4])

# Results
x,y = affine_transformation(q,1/2,-30,np.array([-5,-5]),True)
print(f"Final position: x = {x}, y = {y}")

# Now, we are gonna do the inverse path to check the results
x,y = affine_transformation(np.array([x,y]),2,30,np.array([5,5]),False)
print("---Comprobations---")
print(f"Should return (3,4) because we did the inverse path: x = {x}, y = {y}")
print("Are both results the same? ", np.array_equal(np.round(q, 3),np.round(np.array([x,y]), 3)))

Final position: x = -1.1160254037844388, y = 0.06698729810778048
---Comprobations---
Should return (3,4) because we did the inverse path: x = 2.9999999999999996, y = 3.9999999999999996
Are both results the same?  True


***Fifth question***

**Transformations between 3D coordinate systems:** Consider two 3D
coordinate systems:

• System A has its origin at (1,1,1) and is aligned with the world axes.

• System B has its origin at (2,2,2) and is rotated by 90◦ around the
Z-axis.

A point **r = (3,3,3)** is given in System A. Compute the transformation matrix to convert this point to System B’s coordinates and
apply it to r.

In [6]:
# Initialization
r = np.array([3,3,3,1])   # r point in System  A

# From System A to World coordinates (origin at (0,0,0))
translation_matrix = np.array([[1,0,0,1],[0,1,0,1],[0,0,1,1],[0,0,0,1]])
r1 = translation_matrix @ r
print("Translation matrix: \n",translation_matrix)
print("Result step 1:",r1)


# System B is rotated by 90 grades around the Z-axis
cos = round(np.cos(np.radians(90)),3)
sin = round(np.sin(np.radians(90)),3)
rotation_matrix = np.array([[cos,-sin,0,0],[sin,cos,0,0],[0,0,1,0],[0,0,0,1]])
r2 = rotation_matrix @ r1
print("Rotation matrix: \n",rotation_matrix)
print("Result step 2: ",r2)

# From World coordinates to System B
# System B -> (x,y,z) -> World Coordinates to System B x - 2, y - 2, z - 2
second_translation_matrix = np.array([[1,0,0,-2],[0,1,0,-2],[0,0,1,-2],[0,0,0,1]])
r3 = second_translation_matrix @ r2
print("Second translation matrix: \n",second_translation_matrix)
print("Result step 3: ",r3)

# Comprobation
transformation_matrix = second_translation_matrix @ rotation_matrix @ translation_matrix
print("---Comprobations---")
print("Transformation matrix: \n", transformation_matrix)
result = transformation_matrix @ r
print("Result obtained based on this matrix:", result)
print("Are both results the same? ", np.array_equal(result,r3))


Translation matrix: 
 [[1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 1]]
Result step 1: [4 4 4 1]
Rotation matrix: 
 [[ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
Result step 2:  [-4.  4.  4.  1.]
Second translation matrix: 
 [[ 1  0  0 -2]
 [ 0  1  0 -2]
 [ 0  0  1 -2]
 [ 0  0  0  1]]
Result step 3:  [-6.  2.  2.  1.]
---Comprobations---
Transformation matrix: 
 [[ 0. -1.  0. -3.]
 [ 1.  0.  0. -1.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]
Result obtained based on this matrix: [-6.  2.  2.  1.]
Are both results the same?  True


***Sixth question:***

**Projection in camera coordinates (3D to 2D):**  Let a point in 3D
camera coordiantes be **P = (1,2,5)**. You are given the following camera
intrinsic matrix **K**:

$$ K = \begin{bmatrix} 1000 & 0 & 500 \\ 0 & 1000 & 500 \\ 0 & 0 & 1 \end{bmatrix}$$

• Project the point **P** onto the 2D imagen plane using the intrinsic
matrix **K**.

• Compute the 2D pixel coordinates of the projected point.

• Explain the meaning for the elements of **K**.

In [7]:
# Initializations
K = np.array([[1000,0,500],[0,1000,500],[0,0,1]])
P = np.array([1,2,5])

# Project the point P onto the 2D imagen plane using the intrinsic matrix K.
image_coordinate = K @ P

# Compute the 2D pixel coordinates of the projected point.
u = image_coordinate[0]/image_coordinate[2]
v = image_coordinate[1]/image_coordinate[2]

# Third point
print("---Explication---")
print("The elements of K are: focal lengths, principal point offset and axis skew")
print("Focal length: Distance between the pinhole and the image plane. In a true pinhole camera, both have the same value (1000)")
print("Principal point offset: It's the point where the optical axis intersects the image plane.(500 and 500)")
print("Axis skew: Causes shear distortion in the projected image, zero in model cameras (0)")

# Comprobations
print("---Comprobations---")
print("Coordenates in the plane:",  image_coordinate)
print("2D coordinates in pixel:", u,v)

---Explication---
The elements of K are: focal lengths, principal point offset and axis skew
Focal length: Distance between the pinhole and the image plane. In a true pinhole camera, both have the same value (1000)
Principal point offset: It's the point where the optical axis intersects the image plane.(500 and 500)
Axis skew: Causes shear distortion in the projected image, zero in model cameras (0)
---Comprobations---
Coordenates in the plane: [3500 4500    5]
2D coordinates in pixel: 700.0 900.0


***Seventh question:***

**General camera model (3D World point to 2D Image points):** Given the following camera parameters:
$$ K = \begin{bmatrix} 1200 & 0 & 640 \\ 0 & 1200 & 360 \\ 0 & 0 & 1 \end{bmatrix}$$

• Intrisic matrix **K**.

• Camera rotation matrix **R** = identity matrix.

• Camera translation **t = (0,0,-10)**.

Transform a 3D world point **X = (2,3,4)** from world coordinates to 2D
image coordinates. You will need to:

• Compute the extrinsic matrix from the rotation and translation.

• Project the point onto the image plane.

• Verify the 2D coordinates in pixels.

In [8]:
# Initializations
K = np.array([[1200,0,640],[0,1200,360],[0,0,1]])
R = np.array([[1,0,0],[0,1,0],[0,0,1]])
t = np.array([0,0,-10])

x = np.array([2,3,4,1])

# Build the intrisic matrix
intrinsic_matrix = np.column_stack((R, t))

# Transform the point into the camera's coordinate system
camera_coordinate = intrinsic_matrix @ x

# Project the point onto the image plane
image_coordinate = K @ camera_coordinate

# Convert to 2D
u = image_coordinate[0]/image_coordinate[2]
v = image_coordinate[1]/image_coordinate[2]

# Final result
print("2D Coordinates in pixels: ",u,v)

2D Coordinates in pixels:  240.0 -240.0


***Eighth question:***

**Image transformation using cv2.warpAffine (2D):** Load an image
using **OpenCV.** You will apply a combination of transformations (translation, rotation, and scaling) to the image.

• First, compute the affine transformation matrix manually using translation (50,30), rotation by 30 grades and scaling by a factor of 1.5.

• Use **OpenCV’s cv2.warpAffine** function to apply the transformation
to the image.

• **Display** both the original and transformed images.

In [9]:
# Initializations
image = cv.imread("cat.jpg")

# Comprobations
if image is None:
    print("Error: Image has not being loaded")
# Transformations...
else:
    # Translation, scaling and rotation matrix
    translation_matrix = np.array([[1, 0, 50], [0, 1, 30], [0, 0, 1]], dtype=np.float32)
    scaling_matrix = np.array([[1.5, 0, 0], [0, 1.5, 0], [0, 0, 1]], dtype=np.float32)
    cos = round(np.cos(np.radians(30)), 3)
    sin = round(np.sin(np.radians(30)), 3)
    rotation_matrix = np.array([[cos, -sin, 0], [sin, cos, 0], [0, 0, 1]], dtype=np.float32)

    # Combine transformations
    transformation_matrix = translation_matrix @ scaling_matrix @ rotation_matrix
    print("Transformation matrix \n",transformation_matrix)

    # Extract the 2x3 part of the transformation matrix
    transformation_matrix_2x3 = transformation_matrix[:2, :3]

    # Applying the transformation to the image
    transformed_image = cv.warpAffine(image, transformation_matrix_2x3, (image.shape[1], image.shape[0]))
    
    # Display
    cv.imshow('Original image', image)
    cv.imshow('Transformed image', transformed_image)
    cv.waitKey(20000) # Wait for 20 seconds
    cv.destroyAllWindows()

Transformation matrix 
 [[ 1.299 -0.75  50.   ]
 [ 0.75   1.299 30.   ]
 [ 0.     0.     1.   ]]


***Ninth question:***

***Order of transformations:*** Let **s = (1,1)** be a point in 2D. Apply the
following transformations in the order specified:

• Rotate by 90◦.

• Scale by a factor of 2.

• Translate by (-1,1).

Now reverse the order of the transformations and apply them again. Observe and explain how the final position of s changes with different transformation orders.

In [10]:
# Initializations
s = np.array([1,1,1])

# Rotation
cos = round(np.cos(np.radians(90)),3)
sin = round(np.sin(np.radians(90)),3)
rotation_matrix = np.array([[cos,-sin,0],[sin,cos,0],[0,0,1]])

# Scale
scale_matrix = np.array([[2,0,0],[0,2,0],[0,0,1]])

# Translation
translation_matrix =  np.array([[1,0,-1],[0,1,1],[0,0,1]])

# First result:
print("First result: \n", rotation_matrix @ scale_matrix @ translation_matrix @ s)

# Second result:
print("Second result: \n",translation_matrix @ scale_matrix @ rotation_matrix @ s)

# Explication:
print("---Explication---")
print("Both results are not equals because matrix multiplication is not commutative, the order of the operations matters.")
print("---Demostration---")
print("First transformation matrix: rotation_matrix @ scale_matrix @ translation_matrix \n", rotation_matrix @ scale_matrix @ translation_matrix)
print("Second transformation matrix: translation_matrix @ scale_matrix @ rotation_matrix \n", translation_matrix @ scale_matrix @ rotation_matrix)

First result: 
 [-4.  0.  1.]
Second result: 
 [-3.  3.  1.]
---Explication---
Both results are not equals because matrix multiplication is not commutative, the order of the operations matters.
---Demostration---
First transformation matrix: rotation_matrix @ scale_matrix @ translation_matrix 
 [[ 0. -2. -2.]
 [ 2.  0. -2.]
 [ 0.  0.  1.]]
Second transformation matrix: translation_matrix @ scale_matrix @ rotation_matrix 
 [[ 0. -2. -1.]
 [ 2.  0.  1.]
 [ 0.  0.  1.]]
