# CS512 --- Computer Vision --- First Assignment
# Antonio Castañares Rodríguez, A20599898
# 09/01/2024, Fall 2024






In [1]:
# Imports
import numpy as np

# Part A: Vectors Operations

In [2]:
# Initialization of vectors
p = np.array([2,-1,4])
q = np.array([0,3,5])
r = np.array([1,2,2])

# Exercise 1: 3p + 2q
print("Exercise 1's solution: ", 3*p+2*q)

# Exercise 2: ˆp = a unit vector in the direction of p
norm_p = np.linalg.norm(p)
print("Exercise 2's solution: ", norm_p)

# Exercise 3: ∥p∥ and the angle of p relative to the positive y − axis
theta_p = np.arccos(p[1]/norm_p)
print("Exercise 3's solution: ", np.degrees(theta_p))

# Exercise 4: The direction cosines of p
print("Exercise 4's solution: ", p/norm_p)

# Exercise 5: The angle between p and q
norm_q = np.linalg.norm(q)
dot_product_p_q = np.dot(p,q)
angle_p_q = np.degrees(np.arccos(dot_product_p_q/(norm_p*norm_q)))
print("Exercise 5's solution: ", angle_p_q)

# Exercise 6: p · q and q · p
print("Exercise 6's solution: ", dot_product_p_q, "and", np.dot(q,p))

# Exercise 7: p · q using the angle between p and q
print("Exercise 7's solution: ", norm_p * norm_q * np.cos(np.radians(angle_p_q)))

# Exercise 8: The scalar projection of q onto ˆp
print("Exercise 8's solution: ", dot_product_p_q/norm_p)

# Exercise 9: A vector that is perpendicular to p
x1 = 1
x2 = 1
x3 = -(2 * x1 - 1 *x2)/4    # 2 * x1 + (-1) * x2 + 4 * x3 = 0 -> Perpendicular condition
print("Exercise 9's solution: ", np.array([x1,x2,x3]))

# Comprobation
norm_x = np.linalg.norm(np.array([x1,x2,x3]))
dot_product_p_x = np.dot(p,np.array([x1,x2,x3]))
angle_p_x = np.degrees(np.arccos(dot_product_p_x/(norm_p*norm_x)))
print("Comprobation: If they are perpendiculars, the angle should be 90: ", angle_p_x)

# Exercise 10: p x q and q x p
pxq = np.cross(p,q)
qxp = np.cross(q,p)
print("Exercise 10's solution: ", pxq, "and", qxp)

# Exercise 11: A vector that is perpendicular to both p and q
norm_pxq = np.linalg.norm(pxq)
dot_product_pxq_q = np.dot(pxq,q)
angle_pxq_q = np.degrees(np.arccos(dot_product_pxq_q/(norm_pxq*norm_q)))
print("Exercise 11's solution: ", angle_pxq_q)

# Exercise 12: The linear dependency between p, q and r
aux = np.column_stack((p,q,r))
is_dependent = np.isclose(np.linalg.det(aux),0)
print("Exercise 12's solution: ", is_dependent)
# Exercise 13: p^Tq and pq^T
p_T = np.transpose(p)
q_T = np.transpose(q)
print("Exercise 13's solution: ", np.dot(p_T,q), "and", np.dot(p,q_T))

Exercise 1's solution:  [ 6  3 22]
Exercise 2's solution:  4.58257569495584
Exercise 3's solution:  102.60438264837919
Exercise 4's solution:  [ 0.43643578 -0.21821789  0.87287156]
Exercise 5's solution:  50.490287713806076
Exercise 6's solution:  17 and 17
Exercise 7's solution:  17.0
Exercise 8's solution:  3.709704134011871
Exercise 9's solution:  [ 1.    1.   -0.25]
Comprobation: If they are perpendiculars, the angle should be 90:  90.0
Exercise 10's solution:  [-17 -10   6] and [17 10 -6]
Exercise 11's solution:  90.0
Exercise 12's solution:  False
Exercise 13's solution:  17 and 17


# Part B: Matrix operations

In [3]:
# Inicialization of matrix
X = np.array([[2,1,0],[-1,3,4],[4,2,-2]])
Y = np.array([[4,-1,2],[3,0,-3],[1,2,1]])
Z = np.array([[2,0,-1],[1,4,5],[3,1,2]])

# Inicialization of vectors
s = np.array([-1,4,0])

# X,Y,Z,s Uncomment to print

In [4]:
# Exercise 1: X + 2Y
print("Exercise 1's solution: ", X+2*Y)

# Exercise 2: XY and YX
print("Exercise 2's solution: ", X*Y, "and ", Y*X)

# Exercise 3: (XY)^T and Y^TX^T
product_transpose = np.transpose(np.dot(X,Y))
transpose_product = np.dot(np.transpose(Y), np.transpose(X))
print("Exercise 3's solution: ", product_transpose, "and ", transpose_product)

# Exercise 4: |X| and |Z|
print("Exercise 4's solution: ", np.linalg.det(X), "and ", np.linalg.det(Z))

# Exercise 5: The matrix (either X,Y or Z) in which the row vectors form an orthogonal set
print("Exercise 5's solutions: ")
OneTwo = False;
OneThree = False;
TwoThree = False;
for i in range(X.shape[0]):
    for j in range(X.shape[0]):
        if i != j and (not OneTwo or not OneThree or not TwoThree):
          if i == 0 and j == 1:
            OneTwo = True;
          elif i == 0 and j == 2:
            OneThree = True;
          elif i == 1 and j == 2:
            TwoThree = True;
          else:
            continue;
          dot_product = np.dot(X[i],X[j])
          print(f"Row {i+1} and row {j+1} = {dot_product}")

OneTwo = False;
OneThree = False;
TwoThree = False
for i in range(Y.shape[0]):
    for j in range(Y.shape[0]):
        if i != j and (not OneTwo or not OneThree or not TwoThree):
          if i == 0 and j == 1:
            OneTwo = True;
          elif i == 0 and j == 2:
            OneThree = True;
          elif i == 1 and j == 2:
            TwoThree = True;
          else:
            continue;
          dot_product = np.dot(Y[i],Y[j])
          print(f"Row {i+1} and row {j+1} = {dot_product}")

OneTwo = False;
OneThree = False;
TwoThree = False
for i in range(Z.shape[0]):
    for j in range(Z.shape[0]):
        if i != j and (not OneTwo or not OneThree or not TwoThree):
          if i == 0 and j == 1:
            OneTwo = True;
          elif i == 0 and j == 2:
            OneThree = True;
          elif i == 1 and j == 2:
            TwoThree = True;
          else:
            continue;
          dot_product = np.dot(Z[i],Z[j])
          print(f"Row {i+1} and row {j+1} = {dot_product}")
# Exercise 6: X^{−1} and Y^{−1}
print("Exercise 6's solution: ", np.linalg.inv(X), "and ", np.linalg.inv(Y))

# Exercise 7: Z^{−1}
print("Exercise 7's solution: ", np.linalg.inv(Z))

# Exercise 8: The product Xs
print("Exercise 8's solution: ", np.dot(X,s))

# Exercise 9: The scalar projection of the rows of X onto the vector s (with s normalized)
norm_s = np.linalg.norm(s)
print("Exercise 9's solution: ")
for i in range(X.shape[0]):
    print(np.dot(X[i],s/norm_s))      # Scalar projection = (v · s)||s||

# Exercise 10: The vector projection of the rows of X onto the vector s (with s normalized)
ss = norm_s**2
print("Exercise 10's solution: ")
for i in range(X.shape[0]):
    print(((np.dot(X[i],s))/ss)*s)    # Vector projection = ((v * s)/(s * s))s

# Exercise 11: The linear combination of the columns of X using the elements of s
print("Exercise 11's solution: ", np.dot(X,s))

# Exercise 12: The solution t for the equation Y t=s

# AX=B, being:
# A our matrix of coefficients (Y),
# X our vectors of unknows (t)
# B our vectors of constants (s)
t = np.linalg.solve(Y,s)
print("Exercise 12's solution: ", t)

# Exercise 13: The solution t for the equation Z t=s and the reason for it
t = np.linalg.solve(Z,s)
print("Exercise 13's solution: ", t)

Exercise 1's solution:  [[10 -1  4]
 [ 5  3 -2]
 [ 6  6  0]]
Exercise 2's solution:  [[  8  -1   0]
 [ -3   0 -12]
 [  4   4  -2]] and  [[  8  -1   0]
 [ -3   0 -12]
 [  4   4  -2]]
Exercise 3's solution:  [[11  9 20]
 [-2  9 -8]
 [ 1 -7  0]] and  [[11  9 20]
 [-2  9 -8]
 [ 1 -7  0]]
Exercise 4's solution:  -14.000000000000004 and  17.0
Exercise 5's solutions: 
Row 1 and row 2 = 1
Row 1 and row 3 = 10
Row 2 and row 3 = -6
Row 1 and row 2 = 6
Row 1 and row 3 = 4
Row 2 and row 3 = 0
Row 1 and row 2 = -3
Row 1 and row 3 = 4
Row 2 and row 3 = 17
Exercise 6's solution:  [[ 1.         -0.14285714 -0.28571429]
 [-1.          0.28571429  0.57142857]
 [ 1.          0.         -0.5       ]] and  [[ 0.14285714  0.11904762  0.07142857]
 [-0.14285714  0.04761905  0.42857143]
 [ 0.14285714 -0.21428571  0.07142857]]
Exercise 7's solution:  [[ 0.17647059 -0.05882353  0.23529412]
 [ 0.76470588  0.41176471 -0.64705882]
 [-0.64705882 -0.11764706  0.47058824]]
Exercise 8's solution:  [ 2 13  4]
Exercise 9

# Part C: Eigenvalues and eigenvectors

In [5]:
# Inicialization of matrix
M = np.array([[3,2],[-1,4]])
N = np.array([[5,-3],[-3,6]])
P = np.array([[2,4],[4,8]])

# M,N,P Uncomment to print

In [6]:
# Exercise 1: The eigenvalues and corresponding eigenvectors of M
eigenvectors_M = np.linalg.eig(M)
print("Exercise 1's solutions: ", eigenvectors_M[0], "and ", eigenvectors_M[1])

# Exercise 2: The dot product between the eigenvectors of M
print("Exercise 2's solution: ", np.dot(eigenvectors_M[1][0],eigenvectors_M[1][1]))
# Exercise 3: The dot product between the eigenvectors of N
eigenvectors_N = np.linalg.eig(N)
print("Exercise 3's solutions: ", np.dot(eigenvectors_N[1][0],eigenvectors_N[1][1]))
# Exercise 4: The property of the eigenvectors of N and the reason for it (
print("Exercise 4's solution: The property of the eigenvectors is that all of them are orthogonal (perpendicular) to each \
other. For this reason, the dot product of any pair of eigenvectors is zero")
# Exercise 5: The value of a trivial solution t to the equation P t=0
Z = np.zeros((2,1))
X = np.linalg.lstsq(P,Z, rcond=None)[0]
print("Exercise 5's solution: ", X)
# Exercise 6: The value of two non-trivial solutions t to the equation P t=0

# Exercise 7: The only solution t to the equation M t=0 and the reason for having a single solution
Z = np.zeros((2,1))
X = np.linalg.lstsq(M,Z, rcond=None)[0]
print("Exercise 7's solution: ", X)
print("Explication: The reason for having a single solution is that the matrix M is non-singular. M is invertible, \
and therefore, there are no non-trivial solutiions to this system")

Exercise 1's solutions:  [3.5+1.32287566j 3.5-1.32287566j] and  [[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415+0.54006172j 0.20412415-0.54006172j]]
Exercise 2's solution:  (0.33333333333333337+0j)
Exercise 3's solutions:  0.0
Exercise 4's solution: The property of the eigenvectors is that all of them are orthogonal (perpendicular) to each other. For this reason, the dot product of any pair of eigenvectors is zero
Exercise 5's solution:  [[0.]
 [0.]]
Exercise 7's solution:  [[0.]
 [0.]]
Explication: The reason for having a single solution is that the matrix M is non-singular. M is invertible, and therefore, there are no non-trivial solutiions to this system


# Part D: Neural Network Basic

In [7]:
# Activation functions

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

In [8]:
# Exercise 1: Given a neuron with input values x1 = 0.5, x2 = −0.8 and x3 = 0.3, weights w1 = 0.4, w2 = −0.6 and
# w3 = 0.9 and a bias b = 0.2, compute the output of the neuron before applying any activation function.
W = np.array([0.4,-0.6,0.9])
X = np.array([0.5,-0.8,0.3])
b = 0.2

output_neuron = np.dot(W,X)+b
print("Exercise 1's solution: ", output_neuron)
# Exercise 2: Using the output computed in the previous question, apply the sigmoid activation function to find the
# activation value.
print("Exercise 2's solution: ", sigmoid(output_neuron))
# Exercise 3: Given the same input values and weights as in question 1, compute the output of the neuron after
# applying a ReLU activation function.
print("Exercise 3's solution: ", relu(output_neuron))
# Exercise 4: Given a neural network layer with weights Wh, bias bh, and input x, as follows:
W = np.array([[0.4,0.3],[0.2,0.7]])
x = np.array([1,2])
b = np.array([0.1,-0.1])

# compute the output of the layer using sigmoid activation.
output_neuron = np.dot(W,x)+b
print("Exercise 4's solution: ", sigmoid(output_neuron))
# Exercise 5: Feed the output of the layer from the previous question into an output layer with weights Wh, bias bh,
# as follows:
W = np.array([0.5,-0.3])
b = 0.1

print("Exercise 5's solution: ", np.dot(W,output_neuron)+b)

Exercise 1's solution:  1.15
Exercise 2's solution:  0.759510916949111
Exercise 3's solution:  1.15
Exercise 4's solution:  [0.75026011 0.81757448]
Exercise 5's solution:  0.20000000000000015
